# Generated by Django 4.0.6 on 2022-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='아이디어명')),
                ('description', models.TextField(verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(verbose_name='아이디어 관심도')),
                ('expected_tool', models.CharField(max_length=50, verbose_name='예상 개발툴')),
            ],
        ),
    ]
